### ISSUE TITLE
Scanning css files

### ISSUE THREAD

**Issue by codedbypaul** [doctyper/gulp-modernizr#29]
Is it possible to scan for Modernizr references in css files and build a custom Modernizr based on those?

**Comment by robwierzbowski** [comment]
Since this project uses customizr, I believe it is. +1 for documentation though. Maybe one of us should play with it and write a pull request?

**Comment by knynkwl** [comment]
A little late, I looked into this, and the way that customizr works, is by looking for the present of a class `.flexbox` and not a css value `display: flex;`, which seems a bit weird to me to **not** have an option to switch that functionality.

**Comment by codedbypaul** [comment]
Yeah I see now it does work with CSS files if you use any classes that would normally get appended to the html tag by Modernizr.

So if you have .svg or .flexbox etc then it'll add svg and flexbox to the custom version.
