### ISSUE TITLE
Task "finishes" before it's actually done

### ISSUE THREAD

**Issue by tremby** [doctyper/gulp-modernizr#31]
In the console output with the example code I get "Finished 'modernizr' after x ms", then all my various other tasks (some of which list the modernizr task as a dependency) finish, and _then_ I see the "Looking for Modernizr references" and the other output.

This doesn't work for me: I need the modernizr file to be written before some of the other tasks run.

Am I doing something wrong, or is this a bug?

**Comment by tremby** [comment]
Apologies; I had something wrong. I wasn't returning the stream from the gulp task.

**Comment by tremby** [comment]
Actually I'll reopen this, since the example code does not return the stream. It really should.

```
var modernizr = require('gulp-modernizr');

gulp.task('modernizr', function() {
  gulp.src('./js/*.js')
    .pipe(modernizr())
    .pipe(gulp.dest("build/"))
});
```

For dependencies to work properly this task should return the stream.

**Comment by Hiswe** [comment]
@tremby I may be wrong in your case but you should add a `return` before the `gulp.src`

```js
gulp.task('modernizr', function() {
  // return the stream
  return gulp.src('./js/*.js')
    .pipe(modernizr())
    .pipe(gulp.dest("build/"))
});
```

And for running tasks in sequence easily, you can use [run-sequence](https://www.npmjs.com/package/run-sequence) until gulp 4 is out.

**Comment by tremby** [comment]
Yup, if you read above you'll see that I found you're right. See the later comment for the reason I left this open. Thanks!
